unbound:
  build: .
  ports:
  - "53:53/udp"
  - "53:53"
  environment:
  - BLOCK_ADS=yes
  - BLOCK_SERVER_PROVIDER="yoyo"
  - UPDATE_ROOT_DNS_SERVERS="yes"
  - NUM_THREADS=1
  - SO_RCVBUFF=0
  - SO_SNDBUF=0
  - CACHE_MIN_TTL=360
  - CACHE_MAX_TTL=86400
  - CACHE_MAX_NEGATIVE_TTL=3600
  restart: always
