version: '3.5'

services:
    unbound:
        build:
            context: https://github.com/leleobhz/unbound-dns-dockerized.git
            dockerfile: Dockerfile
        restart: always
        ports:
            - "127.0.0.1:53:53/udp"
            - "127.0.0.1:53:53/tcp"
        environment:
            - BLOCK_ADS=yes
            - BLOCK_SERVER_PROVIDER="yoyo"
            - NUM_THREADS=1
            - SO_RCVBUFF=0
            - SO_SNDBUF=0
            - CACHE_MIN_TTL=360
            - CACHE_MAX_TTL=86400
            - CACHE_MAX_NEGATIVE_TTL=3600
